### ISSUE TITLE
Is there a way to launch jqi from the terminal?

### ISSUE THREAD

**Issue by eugeneware** [nire0510/jqi#2]
Would be awesome to do:

```
$ npm i -g jqi
$ jqi myfile.json
```

or at the very least:

```
$ open -a 'jqi' myfile.json
```

**Comment by nire0510** [comment]
Hello again, @eugeneware!

Glad to update that a newer version is available - **1.4.8**.
With this version you can achieve exactly what you wrote above. An example:
`open /Applications/jqi.app --args -f _ABSOLUTE_PATH_TO_VALID_JSON_FILE_`
