### ISSUE TITLE
Support for newline delimited JSON?

### ISSUE THREAD

**Issue by eugeneware** [nire0510/jqi#3]
I was drawn to the awesome jqi due to a sane way to handle very large json files.

A lot of very large JSON comes in the form of newline delimited JSON which is not valid JSON and thus doesn't work with jqi out of the box. Though `jq` works fine with it from the terminal.

I wrote a small tool called https://github.com/eugeneware/jsonlines2json that convert between the two so I can use jqi, but it would be great if jqi could support this out of the box.

Love your work, and I'm very surprised that there aren't more tools to deal with huge JSON files given the prevalence of it out there!

**Comment by nire0510** [comment]
Hello, @eugeneware

Thank you for your suggestion! Since using newline delimited JSON is not that common, I haven't included this feature in the new version. I'll keep you posted if and when JQI will offer support in such files. Thanks!
