### ISSUE TITLE
jqi fails silently when you load large files

### ISSUE THREAD

**Issue by eugeneware** [nire0510/jqi#4]
When I try load large JSON files (eg. > 500mb) jqi fails silently and doesn't open the file.

**Comment by nire0510** [comment]
Hi Eugene! thank you for your feedback.
500MB files are quite large, I must say, but I have changed JQI settings to accept 1GB files on the next version release (1.5.0)

**Comment by nire0510** [comment]
@eugeneware version 1.4.8 now supports large JSON files.
