### ISSUE TITLE
Allow import of .geojson files

### ISSUE THREAD

**Issue by yuletide** [nire0510/jqi#5]
Currently errors and says "not valid json" even if it is

**Comment by nire0510** [comment]
@yuletide sure, can you please attach an example file?

**Comment by yuletide** [comment]
Sure, I think the fix is mostly to update the filepicker filter to allow for the extension, since geojson files are a valid subset of json: http://geojson.org/

**Comment by nire0510** [comment]
@yuletide thanks. Problem was with the content type of the file. geojson file content type should be `application/geo+json`, while most of the example files out there are simple text ascii files.
I have changed the code, it accepts now *.geojson files.
Make sure you install the latest version: **1.4.11**.

Thanks!
